In [3]:
import boto3
import pandas as pd
import numpy as np

In [3]:
def download_file_from_s3(bucket, object_name, local_file_name):
    """
    Download a file from S3 to the local file system.

    :param bucket: Name of the S3 bucket
    :param object_name: S3 object name
    :param local_file_name: Local file name to save the downloaded file
    """
    # # When using IAM roles, boto3 retrieves credentials from the instance metadata
    # s3_client = boto3.client('s3')

    #When setting up credentials locally, use the following code
    session = boto3.Session()
    s3_client = session.client('s3')

    s3_client.download_file(bucket, object_name, local_file_name)

bucket_name = 'myukdata'
s3_file_name = 'Original/WrittenQA/WrittenQA.csv'
local_file = 'WrittenQA.csv'

download_file_from_s3(bucket_name, s3_file_name, local_file)

In [4]:
df = pd.read_csv('WrittenQA.csv')
df.info()
pd.set_option('display.max_rows', None)
df.head()

/var/folders/nm/l2c6vmjx5jqc1c8c45pgqkh00000gn/T/ipykernel_30194/56142838.py:1: DtypeWarning: Columns (16,17,22,23,26,27) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('WrittenQA.csv')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 475620 entries, 0 to 475619
Data columns (total 32 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   writtenQAID                  475620 non-null  int64
 1   links                        475620 non-null  object
 2   value.id                     475620 non-null  int64
 3   value.askingMemberId         475620 non-null  int64
 4   value.askingMember           0 non-null       float64
 5   value.house                  475620 non-null  object
 6   value.memberHasInterest      475620 non-null  bool
 7   value.dateTabled             475620 non-null  object
 8   value.dateForAnswer          475620 non-null  object
 9   value.uin                    475620 non-null  object
 10  value.questionText           475620 non-null  object
 11  value.answeringBodyId        475620 non-null  int64
 12  value.answeringBodyName      475620 non-null  object
 13  value.isWithdrawn            475620 non-null  bool
 14  value.isNamedDay             475620 non-null  bool
 15  value.groupedQuestions       475620 non-null  object
 16  value.answerIsHolding        473763 non-null  object
 17  value.answerIsCorrection     473763 non-null  object
 18  value.answeringMemberId      473763 non-null  float64
 19  value.answeringMember        0 non-null       float64
 20  value.correctingMemberId     1826 non-null    float64
 21  value.correctingMember       0 non-null       float64
 22  value.dateAnswered           473763 non-null  object
 23  value.answerText             473763 non-null  object
 24  value.originalAnswerText     0 non-null       float64
 25  value.comparableAnswerText   0 non-null       float64
 26  value.dateAnswerCorrected    1825 non-null    object
 27  value.dateHoldingAnswer      18230 non-null   object
 28  value.attachmentCount        475620 non-null  int64
 29  value.heading                474079 non-null  object
 30  value.attachments            475620 non-null  object
 31  value.groupedQuestionsDates  475620 non-null  object
dtypes: bool(3), float64(7), int64(5), object(17)
memory usage: 106.6+ MB

,writtenQAID,links,value.id,value.askingMemberId,value.askingMember,value.house,value.memberHasInterest,value.dateTabled,value.dateForAnswer,value.uin,...,value.dateAnswered,value.answerText,value.originalAnswerText,value.comparableAnswerText,value.dateAnswerCorrected,value.dateHoldingAnswer,value.attachmentCount,value.heading,value.attachments,value.groupedQuestionsDates
0,0,"[{'rel': 'self', 'href': '/Questions/1671415',...",1671415,4131,NaN,Commons,False,2023-11-20T00:00:00,2023-11-23T00:00:00,2744,...,2023-11-23T00:00:00,"The Foreign, Commonwealth and Development Offi...",NaN,NaN,NaN,NaN,0,NaN,[],[]
1,0,"[{'rel': 'self', 'href': '/Questions/1668982',...",1668982,400,NaN,Commons,False,2023-11-09T00:00:00,2023-11-13T00:00:00,1027,...,2023-11-17T00:00:00,The table below has a list of countries covere...,NaN,NaN,2023-11-23T00:00:00,NaN,0,Military Attach√©s,[],[]
2,0,"[{'rel': 'self', 'href': '/Questions/1670571',...",1670571,4934,NaN,Commons,False,2023-11-16T00:00:00,2023-11-23T00:00:00,2386,...,2023-11-23T00:00:00,The Government agreed a deal with the mobile n...,NaN,NaN,NaN,NaN,0,NaN,[],[]
3,0,"[{'rel': 'self', 'href': '/Questions/1669972',...",1669972,4651,NaN,Commons,False,2023-11-14T00:00:00,2023-11-16T00:00:00,1964,...,2023-11-23T00:00:00,The UK is a strong supporter of the Internatio...,NaN,NaN,NaN,NaN,0,Gaza: Armed Conflict,[],[]
4,0,"[{'rel': 'self', 'href': '/Questions/1671311',...",1671311,1409,NaN,Commons,False,2023-11-20T00:00:00,2023-11-23T00:00:00,2522,...,2023-11-23T00:00:00,Existing product safety laws already apply to ...,NaN,NaN,NaN,NaN,0,NaN,[],[]

In [5]:
df.drop(columns=['writtenQAID',
                 'value.askingMember',
                 'value.answeringMember',
                 'value.correctingMember',
                 'value.originalAnswerText',
                 'value.comparableAnswerText',
                 'value.dateAnswerCorrected',
                 'value.dateHoldingAnswer',
                 'links',
                 'value.attachments',
                 'value.attachmentCount',
                 'value.groupedQuestionsDates',
                 'value.groupedQuestions',
                 'value.correctingMemberId'], inplace=True)

df.rename(columns={'value.id': 'writtenQAId',
                     'value.askingMemberId': 'memberId',
                     'value.house':'house',
                     'value.memberHasInterest':'memberHasInterest',
                     'value.dateTabled':'dateTabled',
                     'value.dateForAnswer':'dateForAnswer',
                     'value.uin':'uin',
                     'value.questionText':'questionText',
                     'value.answeringBodyId':'answeringBodyId',
                     'value.answeringBodyName':'answeringBodyName',
                     'value.isWithdrawn':'isWithdrawn',
                     'value.isNamedDay':'isNamedDay',
                     'value.answerIsHolding':'answerIsHolding',
                     'value.answerIsCorrection':'answerIsCorrection',
                     'value.answeringMemberId':'answeringMemberId',
                     'value.dateAnswered':'dateAnswered',
                     'value.answerText':'answerText',
                     'value.heading':'heading'}, inplace=True)


df['dateTabled'] = pd.to_datetime(df['dateTabled'])
df['dateForAnswer'] = pd.to_datetime(df['dateForAnswer'])
df['dateAnswered'] = pd.to_datetime(df['dateAnswered'])

In [6]:
df.head()

,writtenQAId,memberId,house,memberHasInterest,dateTabled,dateForAnswer,uin,questionText,answeringBodyId,answeringBodyName,isWithdrawn,isNamedDay,answerIsHolding,answerIsCorrection,answeringMemberId,dateAnswered,answerText,heading
0,1671415,4131,Commons,False,2023-11-20,2023-11-23,2744,"To ask the Minister of State, Foreign, Commonw...",208,"Foreign, Commonwealth and Development Office",False,True,False,False,1211.0,2023-11-23,"The Foreign, Commonwealth and Development Offi...",NaN
1,1668982,400,Commons,False,2023-11-09,2023-11-13,1027,"To ask the Secretary of State for Defence, whi...",11,Ministry of Defence,False,False,False,True,4528.0,2023-11-17,The table below has a list of countries covere...,Military Attach√©s
2,1670571,4934,Commons,False,2023-11-16,2023-11-23,2386,"To ask the Secretary of State for Science, Inn...",216,"Department for Science, Innovation and Technology",False,True,False,False,39.0,2023-11-23,The Government agreed a deal with the mobile n...,NaN
3,1669972,4651,Commons,False,2023-11-14,2023-11-16,1964,"To ask the Minister of State, Foreign, Commonw...",208,"Foreign, Commonwealth and Development Office",False,False,False,False,4033.0,2023-11-23,The UK is a strong supporter of the Internatio...,Gaza: Armed Conflict
4,1671311,1409,Commons,False,2023-11-20,2023-11-23,2522,To ask the Secretary of State for Business and...,214,Department for Business and Trade,False,True,False,False,4474.0,2023-11-23,Existing product safety laws already apply to ...,NaN

In [7]:
#Save the file to S3
import boto3
import io

def upload_df_to_s3(df, bucket, object_name):
    """
    Upload a DataFrame to an S3 bucket as CSV.

    :param df: DataFrame to upload
    :param bucket: Bucket to upload to
    :param object_name: S3 object name
    :return: True if the DataFrame was uploaded, else False
    """
    # Create a buffer
    csv_buffer = io.StringIO()
    df.to_csv(csv_buffer, index=False)

    # Move to the start of the buffer
    csv_buffer.seek(0)

    # Upload the buffer content to S3
    s3_client = boto3.client('s3')
    try:
        s3_client.put_object(Bucket=bucket, Key=object_name, Body=csv_buffer.getvalue())
    except ClientError as e:
        logging.error(e)
        return False
    return True

bucket_name = 'myukdata'
object_name = 'Preprocessing/WrittenQA/WrittenQA.csv'
upload_df_to_s3(df, bucket_name, object_name)

True