In [9]:
import boto3
import pandas as pd
import numpy as np

In [10]:
def download_file_from_s3(bucket, object_name, local_file_name):
    """
    Download a file from S3 to the local file system.

    :param bucket: Name of the S3 bucket
    :param object_name: S3 object name
    :param local_file_name: Local file name to save the downloaded file
    """
    # # When using IAM roles, boto3 retrieves credentials from the instance metadata
    # s3_client = boto3.client('s3')

    #When setting up credentials locally, use the following code
    session = boto3.Session()
    s3_client = session.client('s3')

    s3_client.download_file(bucket, object_name, local_file_name)

bucket_name = 'myukdata'
s3_file_name = 'Original/Member/Member/Member.csv'
local_file = 'Member.csv'

download_file_from_s3(bucket_name, s3_file_name, local_file)

In [11]:
df = pd.read_csv('Member.csv')
df.info()
pd.set_option('display.max_rows', None)
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4788 entries, 0 to 4787
Data columns (total 33 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   links                                                           4788 non-null   object
 1   value.id                                                        4788 non-null   int64
 2   value.nameListAs                                                4788 non-null   object
 3   value.nameDisplayAs                                             4788 non-null   object
 4   value.nameFullTitle                                             4788 non-null   object
 5   value.nameAddressAs                                             1785 non-null   object
 6   value.latestParty.id                                            4785 non-null   float64
 7   value.latestParty.name                                          4785 non-null   object
 8   value.latestParty.abbreviation                                  4650 non-null   object
 9   value.latestParty.backgroundColour                              4642 non-null   object
 10  value.latestParty.foregroundColour                              4635 non-null   object
 11  value.latestParty.isLordsMainParty                              4785 non-null   object
 12  value.latestParty.isLordsSpiritualParty                         4785 non-null   object
 13  value.latestParty.governmentType                                3044 non-null   float64
 14  value.latestParty.isIndependentParty                            4785 non-null   object
 15  value.gender                                                    4788 non-null   object
 16  value.latestHouseMembership.membershipFrom                      4785 non-null   object
 17  value.latestHouseMembership.membershipFromId                    4785 non-null   float64
 18  value.latestHouseMembership.house                               4788 non-null   int64
 19  value.latestHouseMembership.membershipStartDate                 4788 non-null   object
 20  value.latestHouseMembership.membershipEndDate                   3320 non-null   object
 21  value.latestHouseMembership.membershipEndReason                 2514 non-null   object
 22  value.latestHouseMembership.membershipEndReasonNotes            320 non-null    object
 23  value.latestHouseMembership.membershipEndReasonId               2514 non-null   float64
 24  value.latestHouseMembership.membershipStatus                    0 non-null      float64
 25  value.thumbnailUrl                                              4788 non-null   object
 26  value.latestHouseMembership.membershipStatus.statusIsActive     1468 non-null   object
 27  value.latestHouseMembership.membershipStatus.statusDescription  1468 non-null   object
 28  value.latestHouseMembership.membershipStatus.statusNotes        5 non-null      object
 29  value.latestHouseMembership.membershipStatus.statusId           1468 non-null   float64
 30  value.latestHouseMembership.membershipStatus.status             1468 non-null   float64
 31  value.latestHouseMembership.membershipStatus.statusStartDate    1468 non-null   object
 32  value.latestParty                                               0 non-null      float64
dtypes: float64(8), int64(2), object(23)
memory usage: 1.2+ MB

,links,value.id,value.nameListAs,value.nameDisplayAs,value.nameFullTitle,value.nameAddressAs,value.latestParty.id,value.latestParty.name,value.latestParty.abbreviation,value.latestParty.backgroundColour,...,value.latestHouseMembership.membershipEndReasonId,value.latestHouseMembership.membershipStatus,value.thumbnailUrl,value.latestHouseMembership.membershipStatus.statusIsActive,value.latestHouseMembership.membershipStatus.statusDescription,value.latestHouseMembership.membershipStatus.statusNotes,value.latestHouseMembership.membershipStatus.statusId,value.latestHouseMembership.membershipStatus.status,value.latestHouseMembership.membershipStatus.statusStartDate,value.latestParty
0,"[{'rel': 'self', 'href': '/Members/1', 'method...",1,"Hall, Patrick",Patrick Hall,Patrick Hall,NaN,15.0,Labour,Lab,ff0000,...,2.0,NaN,https://members-api.parliament.uk/api/Members/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'rel': 'self', 'href': '/Members/2', 'method...",2,"Hopkins, Kelvin",Kelvin Hopkins,Kelvin Hopkins,Kelvin Hopkins,8.0,Independent,Ind,C0C0C0,...,12.0,NaN,https://members-api.parliament.uk/api/Members/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'rel': 'self', 'href': '/Members/3', 'method...",3,"Moran, Margaret",Margaret Moran,Margaret Moran,Margaret Moran,8.0,Independent,Ind,C0C0C0,...,11.0,NaN,https://members-api.parliament.uk/api/Members/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'rel': 'self', 'href': '/Members/4', 'method...",4,"Sayeed, Mr Jonathan",Mr Jonathan Sayeed,Mr Jonathan Sayeed,NaN,9.0,Independent Conservative,Ind Con,0000FF,...,NaN,NaN,https://members-api.parliament.uk/api/Members/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'rel': 'self', 'href': '/Members/5', 'method...",5,"Lyell of Markyate, L.",The Lord Lyell of Markyate,The Rt Hon. the Lord Lyell of Markyate QC,NaN,4.0,Conservative,Con,0000ff,...,1.0,NaN,https://members-api.parliament.uk/api/Members/...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.drop(columns=['links',
                 'value.nameDisplayAs',
                 'value.nameAddressAs',
                 'value.latestParty.backgroundColour',
                 'value.latestParty.foregroundColour',
                 'value.latestParty.governmentType',
                 'value.latestHouseMembership.membershipStatus',
                 'value.latestHouseMembership.membershipEndReasonId',
                 'value.thumbnailUrl',
                 'value.latestHouseMembership.membershipStatus.statusIsActive',
                 'value.latestHouseMembership.membershipStatus.statusDescription',
                 'value.latestHouseMembership.membershipStatus.statusNotes',
                 'value.latestHouseMembership.membershipStatus.statusId',
                 'value.latestHouseMembership.membershipStatus.status',
                 'value.latestHouseMembership.membershipStatus.statusStartDate',
                 'value.latestParty',
                 'value.latestParty.abbreviation',
                 'value.latestHouseMembership.membershipEndReasonNotes'], inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4788 entries, 0 to 4787
Data columns (total 15 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   value.id                                         4788 non-null   int64
 1   value.nameListAs                                 4788 non-null   object
 2   value.nameFullTitle                              4788 non-null   object
 3   value.latestParty.id                             4785 non-null   float64
 4   value.latestParty.name                           4785 non-null   object
 5   value.latestParty.isLordsMainParty               4785 non-null   object
 6   value.latestParty.isLordsSpiritualParty          4785 non-null   object
 7   value.latestParty.isIndependentParty             4785 non-null   object
 8   value.gender                                     4788 non-null   object
 9   value.latestHouseMembership.membershipFrom       4785 non-null   object
 10  value.latestHouseMembership.membershipFromId     4785 non-null   float64
 11  value.latestHouseMembership.house                4788 non-null   int64
 12  value.latestHouseMembership.membershipStartDate  4788 non-null   object
 13  value.latestHouseMembership.membershipEndDate    3320 non-null   object
 14  value.latestHouseMembership.membershipEndReason  2514 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 561.2+ KB

In [14]:
df.rename(columns={'value.id': 'memberId',
                     'value.nameListAs': 'fullName',
                     'value.nameFullTitle': 'fullTitle',
                     'value.latestParty.id': 'latestPartyId',
                     'value.latestParty.name': 'partyName',
                     'value.latestParty.isLordsMainParty': 'isLordsMainParty',
                     'value.latestParty.isLordsSpiritualParty': 'isLordsSpiritualParty',
                     'value.latestParty.isIndependentParty': 'isIndependentParty',
                     'value.gender': 'gender',
                     'value.latestHouseMembership.membershipFrom': 'membershipFrom',
                     'value.latestHouseMembership.membershipFromId': 'membershipFromId',
                     'value.latestHouseMembership.house': 'house',
                     'value.latestHouseMembership.membershipStartDate': 'membershipStartDate',
                     'value.latestHouseMembership.membershipEndDate': 'membershipEndDate',
                     'value.latestHouseMembership.membershipEndReason': 'membershipEndReason'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4788 entries, 0 to 4787
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   memberId               4788 non-null   int64
 1   fullName               4788 non-null   object
 2   fullTitle              4788 non-null   object
 3   latestPartyId          4785 non-null   float64
 4   partyName              4785 non-null   object
 5   isLordsMainParty       4785 non-null   object
 6   isLordsSpiritualParty  4785 non-null   object
 7   isIndependentParty     4785 non-null   object
 8   gender                 4788 non-null   object
 9   membershipFrom         4785 non-null   object
 10  membershipFromId       4785 non-null   float64
 11  house                  4788 non-null   int64
 12  membershipStartDate    4788 non-null   object
 13  membershipEndDate      3320 non-null   object
 14  membershipEndReason    2514 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 561.2+ KB

In [15]:
df['membershipStartDate'].describe()

count                    4788
unique                   2436
top       1997-05-01T00:00:00
freq                      227
Name: membershipStartDate, dtype: object

In [16]:
#Save the file to S3
import boto3
import io

def upload_df_to_s3(df, bucket, object_name):
    """
    Upload a DataFrame to an S3 bucket as CSV.

    :param df: DataFrame to upload
    :param bucket: Bucket to upload to
    :param object_name: S3 object name
    :return: True if the DataFrame was uploaded, else False
    """
    # Create a buffer
    csv_buffer = io.StringIO()
    df.to_csv(csv_buffer, index=False)

    # Move to the start of the buffer
    csv_buffer.seek(0)

    # Upload the buffer content to S3
    s3_client = boto3.client('s3')
    try:
        s3_client.put_object(Bucket=bucket, Key=object_name, Body=csv_buffer.getvalue())
    except ClientError as e:
        logging.error(e)
        return False
    return True

bucket_name = 'myukdata'
object_name = 'Preprocessing/Member/Member.csv'
upload_df_to_s3(df, bucket_name, object_name)

True